repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # the release, git tag, or commit you want to use
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=100'] # Maximum size in KB
  - repo: local
    hooks:
      - id: check-file-name
        name: check file name format
        entry: python .githooks/check_file_name.py
        language: python
        require_serial: true
        stages: [pre-commit]
      - id: check-extensions
        name: check extensions for whitelist
        entry: python .githooks/check_extensions.py
        language: python
        require_serial: true
        stages: [pre-commit]
        args: [--whitelist, "lisp", "asd", "md", "txt", "sh", "py", "ipynb", "fcg", "html", "css", "js", "yaml", "gitignore", --blacklist]
      - id: check-diff-size
        name: check diff size
        entry: python .githooks/check_diff_size.py
        language: python
        require_serial: true
        stages: [pre-commit]
        args: ["150"] # Maximum diff size in KB