repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # the release, git tag, or commit you want to use
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=100'] # Maximum size in KB
  - repo: local
    hooks:
      - id: check-commit-size
        name: check commit size
        entry: python .githooks/check_commit_size.py
        language: python
        require_serial: true
        stages: [commit]
        args: ["5"] # Maximum size in MB
      - id: check-file-name
        name: check file name format
        entry: python .githooks/check_file_name.py
        language: python
        require_serial: true
        stages: [commit]
      - id: check-extensions
        name: check extensions for whitelist
        entry: python .githooks/check_extensions.py
        language: python
        require_serial: true
        stages: [commit]
        args: ["md", "lisp", "asd", "sh", "py", "ipynb", "txt", "gitignore", "fcg", "html", "css", "js", "yaml"]
      - id: check-diff-size
        name: check diff size
        entry: python .githooks/check_diff_size.py
        language: python
        require_serial: true
        stages: [commit]
        args: ["100"] # Maximum diff size in KB