(ql:quickload :clevr-dialog-grammar)
(in-package :clevr-dialog-grammar)
(activate-monitor trace-fcg)

;; DIALOG 1
(comprehend-all "are there brown digits")
(comprehend-all "are there digits in a yellow background among them")
(comprehend-all "what is the number of the digit above it")
(comprehend "what is the background color of the 1")
(comprehend-all "what is the color of the digit below it")
(comprehend-all "are there more brown digits")
(comprehend-all "are there 0 's among them")
(comprehend "what is the style of it")
(comprehend "what is the color of the digit below it")
(comprehend-all "what is the number of the digit above it")

;; DIALOG 2
(comprehend "are there any digits in a salmon background")
(comprehend "how many 4 's are there among them")
(comprehend-all "what is the style of the 4")
(comprehend-all "what is the color of the digit")
(comprehend-all "what is the background color of the digit above it")
(comprehend-all "what is the color of the digit")
(comprehend "what is the color of the digit")
(comprehend "what is the style of the digit")
(comprehend-all "what is the number of the digit")
(comprehend-all "are there more digits in a yellow background")
(comprehend "are there 5 's among them")


;; DIALOG 3 
(comprehend-all "how many digits in a cyan background are there in the image")
(comprehend-all "what is the number of it")
(comprehend-all "are there other digits in a cyan background")
(comprehend-all "are there other green digits") 
(comprehend-all "are there digits in a salmon background")
(comprehend-all "are there 1 's among them")
(comprehend-all "what is the style of the digit")
(comprehend-all "what is the number of the digit at the right of it")
(comprehend-all "what is the color of the digit below it")
(comprehend-all "what is the background color of it")
(comprehend-all "are there any more green digits")

(comprehend " digits in a yellow background")
(comprehend-all "are there digits with a stroke")
(comprehend-all "are there digits with a stroke")
(comprehend "digits with a stroke")
(comprehend "what is the style of the digit with a stroke")

(comprehend "green digits")
(comprehend "the green digit")
(comprehend "the digit with a stroke")

;; test question comprehension mnist

;; fixed
(comprehend "what is the style of the digit at the left of it")
(comprehend "how many green digits are there")
(comprehend "what is the color of the digit at the left of it")
(comprehend "how many digits in a salmon background are there")
(comprehend "what is the style of the digit at the left of it")
(comprehend-all "what is the number of the blue digit")
(comprehend "what is the background color of the blue digit")
(comprehend-all "what is the number of the violet digit")
(comprehend-all "are there any digits with a stroke among them")
(comprehend "are there other digits with a stroke")
(comprehend "are there any digits with a stroke among them")
(comprehend-all "are there other digits with a stroke")
(comprehend-all "are there other green digits")
(comprehend-all "are there other digits in a yellow background")


;; test question comprehension clevr

;;fixed
(comprehend "what is the material of the above large object")
(comprehend "what color is the above metal object")
(comprehend "what is the shape of the above large object")
(comprehend "what is the count of other objects")
(comprehend "are there other objects present in the view sharing its color")
(comprehend "are there other objects that share the same shape with the aforementioned gray object")
(comprehend "if there is an object right of it what material is it")
(comprehend "what size is the above green object")
(comprehend "if there is an object right of the earlier gray object what is its color")
(comprehend "if there is an object in front of the aforementioned brown object what is its color")
(comprehend "if there is an object on the right side of it what shape is it")
(comprehend "does the view have other objects that share the same material with the previous tiny object")
(comprehend "what color is the above tiny object")
(comprehend "what number of other objects in the image share similar shape with the earlier large object")
(comprehend-all "how many other objects have its size")
(comprehend "if there is an object in front of it what color is it")
(comprehend "what is the shape of the above green object")
(comprehend "does the above round object have objects to its behind")
(comprehend "are there objects present in front of itself in the image")
(comprehend "what number of other objects in the picture share similar material with the above cylinder")
(comprehend "any other objects")
(comprehend "if there is an object in front of that cylinder what color is it")
(comprehend "if there is an object in front of it what color is it")
(comprehend "are there other objects that are of same color as the aforementioned green object")
(comprehend "if there is an object in front of that green object what is its shape")
(comprehend "what is the count of objects the above ball has to its behind")
(comprehend "does the scene have other objects that are of same shape as that block")
(comprehend "if there is an object behind it what color is it")
(comprehend "what is the count of other objects in the scene")
(comprehend "are there objects present in front of itself in the image")
(comprehend "are there objects present in front of the earlier cube")
(comprehend "are there objects present to the left of that tiny object")
(comprehend "are there objects to its front")
(comprehend "are there objects to the left of the previous tiny object")
(comprehend "are there objects present to the left of that small object")
(comprehend "are there objects left of the above yellow object")
(comprehend "are there objects right of the earlier big object")
(comprehend "if there is an object to the left of the aforementioned metal object what is its size")
(comprehend "are there objects present on the left side of the previous block")
(comprehend "what is the material of this object")
(comprehend "what is the size of that cylinder")
(comprehend "are there things to the right of the aforementioned rubber thing")
(comprehend "are there things in front of the previous metallic thing")
(comprehend "are there things on the left side of the previous cyan thing")
(comprehend "what is the shape of that metal thing")
(comprehend "are there things present to the right of the aforementioned green thing")
(comprehend "does the picture have other things that share the same size with the above shiny thing")
(comprehend "are there things present behind that purple thing")
(comprehend "are there things right of that metal thing")
(comprehend "what is the count of other objects in the image that share its size")
(comprehend "does the scene have other things that are of same size as the above purple thing")
(comprehend "does the picture have other things that are of same size as the above matte thing")
(comprehend "what is the count of other things that share its material in the view")
(comprehend "does the view have other things that are of same color as the above large thing")
(comprehend "what is the count of other objects that share its shape")
(comprehend "if there is an object to the left of the earlier brown object what is its color")
(comprehend "what number of other objects in the picture are of same shape with the above rubber object")
(comprehend "does the scene have other things that share the same color with the above metallic thing")
(comprehend "what is the count of other things that share its size in the view")



