;(ql:quickload :coco-grammar)
(in-package :coco-grammar)
(activate-monitor trace-fcg)

(comprehend "how many cows are there?")
(comprehend "is there a sheep left of the cow?")
(comprehend "how many sheep are right of the cow?")
(comprehend "what category is the thing left of the dog?")
(comprehend "how many cats are left of the dog and right of the cow?")
(comprehend "how many things are cats or dogs?")
(comprehend "are there an equal number of cows and sheep?")
(comprehend "are there more cows than sheep?")
(comprehend "are there fewer cows than sheep?")
(comprehend "is there a zebra left of the giraffe?")
(comprehend "is there a sea below the sky?")

