(in-package :geoquery-lsfb-grammar-copy)

(def-fcg-constructions geoquery-lsfb-copy
  :feature-types ((subunits set)
                  (args set-of-predicates)
                  (possible-categories set)
                  (footprints set)
                  (hello set)
                  (form set-of-predicates)
                  (meaning set-of-predicates)
                  (boundaries set-of-predicates))
  :hierarchy-features (subunits)
  :diagnostics ()
  :repairs ()
  :fcg-configurations ((:parse-goal-tests :no-applicable-cxns :connected-semantic-network :connected-structure)
                       (:production-goal-tests :no-applicable-cxns :no-meaning-in-root :connected-structure)
                       (:node-tests :check-duplicate :restrict-nr-of-nodes :restrict-search-depth)
                       (:max-number-of-nodes . 3000)
                       (:max-search-depth . 50)
                       (:render-mode . :signed-form-predicates)
                       (:de-render-mode . :signed-form-predicates)
                       (:shuffle-cxns-before-application . t)
                       (:draw-meaning-as-network . t)
                       (:construction-inventory-processor-mode . :heuristic-search)
                       (:node-expansion-mode . :full-expansion)
                       (:search-algorithm . :best-first)
                       (:heuristic-value-mode . :sum-heuristics-and-parent)
                       (:cxn-supplier-mode . :all-cxns)
                       (:heuristics :nr-of-applied-cxns :cxn-score)
                       (:category-linking-mode . :neighbours))
  
  :visualization-configurations ((:with-search-debug-data . t)
                                 (:show-categorial-network . t)
                                 (:remove-empty-units . nil)
                                 (:show-constructional-dependencies . nil)
                                 (:labeled-paths . nil)
                                 (:colored-paths . nil)
                                 (:hide-features . nil)
                                 (:hierarchy-features subunits)
                                 (:selected-hierarchy . subunits)
                                 (:select-subfeatures . nil))
  :cxn-inventory *geoquery-lsfb-copy*)